# Generated by Django 4.2.25 on 2025-10-08 04:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeri', models.CharField(max_length=100)),
                ('ip_manzili', models.GenericIPAddressField(protocol='IPv4')),
                ('is_active', models.BooleanField(default=False)),
                ('jolashuvi', models.CharField(max_length=60)),
                ('koorX', models.FloatField(blank=True, null=True)),
                ('koorY', models.FloatField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('yil', models.DateField(blank=True, null=True)),
                ('toliq_mal', ckeditor.fields.RichTextField()),
                ('javob_shax', models.TextField(blank=True, null=True)),
                ('ichki_nom', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BazaStansiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeri', models.CharField(max_length=100)),
                ('ip_manzili', models.GenericIPAddressField(protocol='IPv4')),
                ('is_active', models.BooleanField(default=False)),
                ('jolashuvi', models.CharField(max_length=60)),
                ('koorX', models.FloatField(blank=True, null=True)),
                ('koorY', models.FloatField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('yil', models.DateField(blank=True, null=True)),
                ('toliq_mal', ckeditor.fields.RichTextField()),
                ('javob_shax', models.TextField(blank=True, null=True)),
                ('ichki_nom', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('holat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ipmanzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeri', models.CharField(max_length=100)),
                ('kategoriya', models.CharField(choices=[('BazaStansiya', 'BazaStansiya'), ('ATS', 'ATS'), ('Kompyuter', 'Kompyuter'), ('Telefon', 'Telefon'), ('Server', 'Server'), ('Printer', 'Printer'), ('Router', 'Router'), ('Panasonic ATS', 'Panasonic ATS'), ('Grandstream ATS', 'Grandstream ATS')], max_length=100)),
                ('ip_manzili', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('jolashuvi', models.CharField(max_length=60)),
                ('koorX', models.FloatField(blank=True, null=True)),
                ('koorY', models.FloatField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('yil', models.DateField(blank=True, null=True)),
                ('toliq_mal', ckeditor.fields.RichTextField()),
                ('javob_shax', ckeditor.fields.RichTextField()),
                ('ichki_nomer', ckeditor.fields.RichTextField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stansiyalar.hudud')),
            ],
        ),
    ]
