# Generated by Django 4.2.25 on 2025-10-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stansiyalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanzil',
            name='kategoriya',
            field=models.CharField(choices=[('BazaStansiya', 'BazaStansiya'), ('GrandStreamATS', 'PanasonicATS'), ('Kompyuter', 'Kompyuter'), ('Telefon', 'Telefon'), ('Server', 'Server'), ('Printer', 'Printer'), ('Router', 'Router'), ('Boshqa', 'Boshqa')], max_length=100),
        ),
    ]
