# Generated by Django 4.2.25 on 2025-10-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stansiyalar', '0004_gats_pats_delete_ats_delete_bazastansiya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gats',
            old_name='kategoriya',
            new_name='turi',
        ),
        migrations.RenameField(
            model_name='pats',
            old_name='kategoriya',
            new_name='toifa',
        ),
    ]
