# Generated by Django 4.2.25 on 2025-10-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stansiyalar', '0006_alter_gats_hudud_alter_ipmanzil_hudud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanzil',
            name='hudud',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ('Toshkent_shahar', 'Toshkent_shahar'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Qashqadaryo', 'Qashqadaryo'), ('Buxoro', 'Buxoro'), ('Surxondaryo', 'Surxondaryo'), ('Navoiy', 'Navoiy'), ('Xorazim', 'Xorazim'), ('Qoraqalpogiston', 'Qoraqalpogiston')], max_length=40),
        ),
    ]
