# Generated by Django 4.2.25 on 2025-10-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stansiyalar', '0008_alter_ipmanzil_hudud_alter_ipmanzil_nomeri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanzil',
            name='nomeri',
            field=models.CharField(max_length=100),
        ),
    ]
