# Generated by Django 4.2.25 on 2025-10-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stansiyalar', '0009_alter_ipmanzil_nomeri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gats',
            name='ip_manzili',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='ipmanzil',
            name='hudud',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Fargona', 'Fargona'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Qashqadaryo', 'Qashqadaryo'), ('Buxoro', 'Buxoro'), ('Surxondaryo', 'Surxondaryo'), ('Navoiy', 'Navoiy'), ('Toshkent_shahar', 'Toshkent_shahar'), ('Xorazim', 'Xorazim'), ('Qoraqalpogiston', 'Qoraqalpogiston')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ipmanzil',
            name='ip_manzili',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='pats',
            name='ip_manzili',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
