# Generated by Django 4.2.25 on 2025-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tadbir',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
