# Generated by Django 4.2.25 on 2025-10-10 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_tadbir_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tadbir',
            name='izoh',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
