# Generated by Django 4.2.25 on 2025-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tadbir_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadbir',
            name='fayl',
            field=models.FileField(blank=True, null=True, upload_to='tadbir_hujjatlari/'),
        ),
    ]
