# Generated by Django 4.2.25 on 2025-10-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tadbir_fayl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadbir',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
