# Generated by Django 4.2.25 on 2025-10-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_tadbir_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadbir',
            name='fayl',
            field=models.ImageField(blank=True, null=True, upload_to='tadbir_hujjatlari/'),
        ),
    ]
