# Generated by Django 4.2.25 on 2025-10-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_tadbir_fayl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadbir',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
